// Wheel entries (1–100) with numbers. Blanks left empty for now.

export const WHEEL_NAMES = [
  '1. Heaven Sent',
  '2. Babylyn Anglo',
  '3. Shiella Jimenez',
  '4. Kimberly Dioquino',
  '5. Kimberly Dioquino',
  '6. Kimberly Dioquino',
  '7. Kimberly Dioquino',
  '8. Babylyn Anglo',
  '9. Heaven Sent',
  '10. Maricel Alvarez',
  '11. Meryll Nicodemus',
  '12. Charles Millare',
  '13. Meryll Nicodemus',
  '14. Heaven Sent',
  '15. Babylyn Anglo',
  '16. Abbygail Valera',
  '17. Maricel Alvarez',
  '18. Cristy Dionaldo',
  '19. Heaven Sent',
  '20. Meryll Nicodemus',
  '21. Rosemarie Anglo',
  '22. Babylyn Anglo',
  '23. Jess Moroda',
  '24. Froilan Valera',
  '25. Froilan Valera',
  '26. Froilan Valera',
  '27. Rosemarie Anglo',
  '28. Cristy Dionaldo',
  '29. Rosemarie Anglo',
  '30. Winalyn Dipon',
  '31. Froilan Valera',
  '32. Catherine Calibuso',
  '33. Michelle Soriano',
  '34. Michelle Soriano',
  '35. Michelle Soriano',
  '36. Michelle Soriano',
  '37. Jasmin Buisan',
  '38. Jasmin Buisan',
  '39. Shirley Ancayan',
  '40. Babylyn Anglo',
  '41. Abram Linezo',
  '42. Rica Manalo',
  '43. Rica Manalo',
  '44. Grae',
  '45. Grae',
  '46. Winalyn Dipon',
  '47. Arcy Bravo Calima',
  '48. KC Angeline',
  '49. JM Fulong',
  '50. JM Fulong',
  '51. Nicole Castuera',
  '52. Rica Manalo',
  '53. Grae',
  '54. Grae',
  '55. Vino Ramos',
  '56. Nenita Valera',
  '57. Princess Cordova',
  '58. Princess Cordova',
  '59. Shirley Ancayan',
  '60. Kimberly de padua',
  '61. Ambies Dulay',
  '62. Jess Moroda',
  '63. KC Angeline',
  '64. Andrea Balajadia',
  '65. Andrea Balajadia',
  '66. Abbygail Valera',
  '67. Ellie',
  '68. Ambies Dulay',
  '69. Kate Gregorio',
  '70. Mimi Barbo',
  '71. MED',
  '72. Anna Basco',
  '73. Jhonvee De Mesa',
  '74. Anna Basco',
  '75. Ella Mae Cas',
  '76. Mimi Barbo',
  '77. Prince Malimban',
  '78. K - Anne Naomi',
  '79. Trisha Lito',
  '80. Cherry Ramos',
  '81. Ambies Dulay',
  '82. Ambies Dulay',
  '83. Joy Jimenez',
  '84. JAYJAY',
  '85. JAYJAY',
  '86. Prince Malimban',
  '87. MED',
  '88. Ate Etch',
  '89. Prince Malimban',
  '90. Mau Manto',
  '91. Catherine Dimaisip',
  '92. Jarmaine Digma',
  '93. Kimberly de padua',
  '94. Sam Moreno',
  '95. Sam Moreno',
  '96. Sam Moreno',
  '97. Nenita Valera',
  '98. Maria Trinidad',
  '99. Maria Trinidad',
  '100. Maria Trinidad',
];

// Final bunot sequence (spins 1–13)
export const DRAW_SEQUENCE = [
  '76. Mimi Barbo',
  '64. Andrea Balajadia',
  '9. Heaven Sent',
  '20. Meryll Nicodemus',
  '12. Charles Millare',
  '56. Nenita Valera',
  '6. Kimberly Dioquino',
  '79. Trisha Lito',
  '3. Shiella Jimenez',
  '28. Cristy Dionaldo',
  '43. Rica Manalo',
  '40. Babylyn Anglo',
  '98. Maria Trinidad',
];
